openapi: 3.0.1
info:
  title: Portal License APIs
  version: "10.11"
  description: |-
    ## Overview
    Developer Portal requires an license to use his functionalities

    This API will cover how to manage the license.

    ## Functionalities supported
    - Add License
    - Get License
    - Delete License

    ## Authorization
    - Users with role 'Administrator' can add/get/delete a license

servers:
  - url: http://localhost:18101/portal/rest/v1
    description: Development server

paths:
  "/licenses":
    get:
      summary: Retrieve all the licenses added to Developer Portal
      description: |-
        Endpoint to retrieve the list of all Linceses in Developer Portal.
      responses:
        '200':
          description: ''
          content:
            application/json:
              example: |-
                [
                  {
                      "name": "license.xml",
                      "product": "DPO",
                      "licenseType": "TEN",
                      "serialNumber": "0006219",
                      "licenseKey": null,
                      "customerName": "SoftwareAG",
                      "expirationDate": null,
                      "expiringUnlimited": true,
                      "productVersion": "10.1",
                      "alert": false
                  }
                ]
        '403':
          $ref: '#/components/responses/Forbidden'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      summary: Upload an License to an Developer Portal
      description: |-
        Endpoint to publish an License to an Developer Portal.

        *Endpoint can be accessed only by a user having **Administrator** role*
      requestBody:
        content:
          multipart/formdata:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: License file in binary format
            example:
              |-
              ------WebKitFormBoundaryOBl7vP7ee7F5cESA
              Content-Disposition: form-data; name="file"; filename="license.xml"
              Content-Type: application/json


              ------WebKitFormBoundaryOBl7vP7ee7F5cESA--
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
              example: |-
                {"code":200,"message":"License is added successfully"}
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '400':
          description: Bad Request
          content:
            application/json:
              examples:
                400:
                  $ref: '#/components/examples/400'

    delete:
      summary: Delete an license
      description: |-
        Endpoint to delete the specific license from an Developer Portal.
      parameters:
        - name: serialNumber
          in: query
          description: serialNumber of an license that need to be deleted
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 'No content'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'


components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            401:
              $ref: '#/components/examples/401'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            403:
              $ref: '#/components/examples/403'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  examples:
    401:
      value:
        code: 401
        message: Invalid credentials
    403:
      value:
        code: 403
        message: Insufficient privileges
    400:
      value:
        code: 400
        message: Invalid file
