openapi: 3.0.1
info:
  title: Portal Notifications API
  description: |
     ## Overview
      - Notifications are alerts on the activities by other users or activities on groups.

     ## Notification Management API
     - Notification Management API helps to manage notifications in API Portal.

     - InApp and Email notifications are supported and they can be turned ON Or OFF by
       changing the preferences for an user in notification settings.

     ## Overview of supported functionalities and Accessibility
     - Owner of the notificaton can view all notifications, get the count of unread notifications, update or
       delete notifications.

  version: "10.11"

servers:
  - url: http://localhost:18101/portal/rest/v1
    description: Development server

paths:
  /users/preferences:
    get:
      summary: Read notification preference
      description: Get the notification preferences of the currently logged in user
      tags:
        - Notification
      responses:
        '200':
          description: Notification Preference of the current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPreference'
              examples:
                NotifictionPreference:
                  $ref: '#/components/examples/NotificationPreference'
        "401":
          $ref: '#/components/responses/Unauthorized'
    put:
      summary: Update notification preference
      description: Update the notification preferences for logged in user
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationPreference'
            examples:
              NotifictionPreference:
                $ref: '#/components/examples/NotificationPreference'
      responses:
        '200':
          description: Notification preference for the current user updated successfully
        "401":
          $ref: '#/components/responses/Unauthorized'
  /notifications:
    get:
      tags:
        - Notification
      summary: Fetch notifications
      description: Retrieve paginated notifications for the currently logged in user
      parameters:
        - name: page
          in: query
          description: Optional parameter. Defines the page number to be retrieved for the collection. If not specified default value 0 is assumed. By default collection responses are paginated with batches of 10.
          required: false
          schema:
            type: integer
      responses:
        "200":
          $ref: '#/components/responses/NotificationListResponse'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
    put:
      tags:
        - Notification
      description: Update the status of notifications as READ or UNREAD
      summary: Mark READ/UNREAD
      parameters:
        - name: status
          in: query
          description: Defines the status of the notification
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: {
                type: string
              }
            example: '["3bdf8005-5685-3ef5-b132-de4681963fb6","3bdf8005-5685-3ef5-b13-de4681963yb6"]'
      responses:
        "200":
          $ref: '#/components/responses/StatusUpdatedResponse'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Notification
      description: Bulk delete of notifications belong to logged in user
      summary: Delete notifications
      requestBody:
        content:
          application/json:
            schema:
              description: Collection of unique identifier for notification
              type: array
              items:
                type: string
            example: '["3bdf8005-5685-3ef5-b132-de4681963fb6","3bdf8005-5685-3ef5-b13-de4681963y0b6"]'
      responses:
        "204":
          description: "Response when given notifications deleted successfully"
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
  /notifications/_count:
    get:
      tags:
        - Notification
      summary: Unread notification count
      description: Retrieves the number of unread notifications for the logged in user
      responses:
        "200":
          $ref: '#/components/responses/UnreadCount'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    NotificationEventType:
      description: type of notifcation generated. sample values `TOPIC_CREATED` / `COMMENT_CREATED` / `APPROVAL_PENDING`
      type: string
      enum:
        - TOPIC_CREATED
        - COMMENT_CREATED
        - APPROVAL_PENDING
        - APPROVAL_RESULT
        - API_REPUBLISH
        - API_UNPUBLISH
        - PACKAGE_REPUBLISH
        - PACKAGE_UNPUBLISH
        - EMAIL_VERIFICATION
    NotificationList:
      type: object
      properties:
        result:
          type: array
          description: Collection of notifications
          items:
            $ref: '#/components/schemas/Notification'
        count:
          type: integer
          description: Total number of notifications available
        _links:
          type: object
          properties:
            _self:
              description: Link for current page
              type: string
            _next:
              description: Optional link for the next page. Will be missing if the next page does not exist.
              type: string
    NotificationUserSignificance:
      type: string
      description: Indicates the significance of the notification message like `INFORMATION`/`ACTION`. Currently supports only Info.
      enum:
        - INFORMATION
        - ACTION
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        errors:
          type: array
          items:
            type: string

    NotificationPreference:
      type: object
      description: Notification preference for the user
      properties:
        inapp:
          $ref: '#/components/schemas/InAppNotification'
        email:
          $ref: '#/components/schemas/EmailNotification'
    InAppNotification:
      type: object
      description: In app notification settings
      additionalProperties:
        $ref: '#/components/schemas/Frequency'
    EmailNotification:
      type: object
      description: Email notification settings
      additionalProperties:
        $ref: '#/components/schemas/Frequency'
    Frequency:
      type: string
      description: Frequency of notification. Valid values `INSTANT` / `DAILY` / `WEEKLY`
      enum:
        - OFF
        - INSTANT
        - DAILY
        - WEEKLY
        - MONTHLY

    Notification:
      type: object
      properties:
        owner:
          description: GUID of the user for whom the notification was generated
          type: string
        localization:
          description: Localized text of notification message
          type: string
        significance:
          $ref: '#/components/schemas/NotificationUserSignificance'
        notification:
          $ref: '#/components/schemas/NotificationEventType'
        name:
          type: string
        context:
          description: context parameters specific to notification generated.
          type: object
          additionalProperties:
            type: string
        id:
          description: Unique identifier of the notification. Usually be a UUID
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/NotificationStatus'
    NotificationStatus:
      type: string
      description: status indicating whether specific notification is read by the user or not. Possible values `READ` / `UNREAD`
      enum:
        - READ
        - UNREAD
    StatusUpdated:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    UnreadCount:
      type: integer
      format: int32
  responses:
    BadRequest:
      description: User provided data is not correct
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            400:
              $ref: '#/components/examples/400'
    NotificationListResponse:
      description: User's notifications are fetched successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotificationList'
          examples:
            NotificationList:
              $ref: '#/components/examples/NotificationList'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            401:
              $ref: '#/components/examples/401'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            403:
              $ref: '#/components/examples/403'
    StatusUpdatedResponse:
      description: Notification status updated successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusUpdated'
          examples:
            StatusUpdatedExample:
              $ref: '#/components/examples/StatusUpdatedExample'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            404:
              $ref: '#/components/examples/404'
    UnreadCount:
      description: Unread notifications count
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnreadCount'
          examples:
            UnreadCountExample:
              $ref: '#/components/examples/UnreadCountExample'
  examples:
    "400":
      value:
        code: 400
        message: User provided data is not correct
    "401":
      value:
        code: 401
        message: Invalid credentials
    StatusUpdatedExample:
      value:
        code: 200
        message: Notification status updated successfully
    "403":
      value:
        code: 403
        message: Insufficient privileges
    "404":
      value:
        code: 404
        message: Unable to find the notification with id [3bdf8005-5685-3ef5-b132-de4681963fb6]
    "NotificationList":
      value:
        count: 1
        _links:
          _self: /rest/v1/packages?page=0
        result:
          - owner: 200ceb26-807d-3bf9-9fd6-f4f0d1ca54d4
            id: 24e7efda-eb9a-4a7c-ade8-27ea4f196b31
            modified: 2021-03-25 11:32 UTC
            created: 2021-03-25 11:32 UTC
            status: UNREAD
            context:
              originator.id: INTERNAL
              api.name: Portal Notifications API
              tenant: default
              api.id: e4d8161b-24b4-479a-aa8f-077e6f4817fd
            localization: Api Portal Notifications API has been unpublished
            notification: API_UNPUBLISH
            significance: INFORMATION

    NotificationPreference:
      value:
        INAPP:
          TOPIC_CREATED: INSTANT
          COMMENT_CREATED: INSTANT
          APPROVAL_PENDING: INSTANT
          APPROVAL_RESULT: INSTANT
          API_REPUBLISH: INSTANT
          API_UNPUBLISH: INSTANT
          PACKAGE_UNPUBLISH: INSTANT
          PACKAGE_REPUBLISH: INSTANT
        EMAIL:
          TOPIC_CREATED: OFF
          COMMENT_CREATED: OFF
          APPROVAL_PENDING: OFF
          APPROVAL_RESULT: OFF
          API_REPUBLISH: INSTANT
          API_UNPUBLISH: INSTANT
          PACKAGE_UNPUBLISH: INSTANT
          PACKAGE_REPUBLISH: INSTANT

    "Notification":
      value:
        - owner: 200ceb26-807d-3bf9-9fd6-f4f0d1ca54d4
          id: 24e7efda-eb9a-4a7c-ade8-27ea4f196b31
          modified: 2021-03-25 11:32 UTC
          created: 2021-03-25 11:32 UTC
          status: UNREAD
          context:
            originator.id: INTERNAL
            api.name: Portal Notifications API
            tenant: default
            api.id: e4d8161b-24b4-479a-aa8f-077e6f4817fd
          localization: Api Portal Notifications API has been unpublished
          notification: API_UNPUBLISH
          significance: INFORMATION
    "UnreadCountExample":
      value:
        3